-- MySQL Script generated by MySQL Workbench
-- 2017년 09월 09일 (토) 오후 05시 00분 08초
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shopping_mall` DEFAULT CHARACTER SET utf8 ;
USE `shopping_mall` ;

-- -----------------------------------------------------
-- Table `shopping_mall`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopping_mall`.`Users` (
  `이메일` CHAR(30) NOT NULL,
  `이름` VARCHAR(45) NULL,
  `주소` VARCHAR(100) NULL,
  `전화번호` VARCHAR(45) NULL,
  `레벨` TINYINT(1) NULL,
  `비밀번호` CHAR(20) NULL,
  PRIMARY KEY (`이메일`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '가입 유저 정보';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
